### ISSUE TITLE
Is it possible to make a context menu entry that runs programs as TI with this?

### ISSUE THREAD

**Issue by ibay770** [mbcdev/RunAsTrustedInstaller#1]
I'm wondering how to make a context menu, Run as TI with this.

**Comment by mbcdev** [comment]
This can be accomplished with a Shell Extension Handler [1], and coincidentally, I had already started working on it some time ago. I took your question as an opportunity to finally complete it. Additional information on how to use it can be found in the README file.

[1] https://learn.microsoft.com/en-us/windows/win32/shell/handlers
